// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: rmtaccessmgr/v1/rmtacessmgr.proto

package remaccessmgrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RmtaccessmgrService_GetRemoteAccessConfigByGuid_FullMethodName = "/rmtaccessmgr.v1.RmtaccessmgrService/GetRemoteAccessConfigByGuid"
)

// RmtaccessmgrServiceClient is the client API for RmtaccessmgrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RmtaccessmgrServiceClient interface {
	GetRemoteAccessConfigByGuid(ctx context.Context, in *GetRemoteAccessConfigByGuidRequest, opts ...grpc.CallOption) (*GetResourceAccessConfigResponse, error)
}

type rmtaccessmgrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRmtaccessmgrServiceClient(cc grpc.ClientConnInterface) RmtaccessmgrServiceClient {
	return &rmtaccessmgrServiceClient{cc}
}

func (c *rmtaccessmgrServiceClient) GetRemoteAccessConfigByGuid(ctx context.Context, in *GetRemoteAccessConfigByGuidRequest, opts ...grpc.CallOption) (*GetResourceAccessConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceAccessConfigResponse)
	err := c.cc.Invoke(ctx, RmtaccessmgrService_GetRemoteAccessConfigByGuid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RmtaccessmgrServiceServer is the server API for RmtaccessmgrService service.
// All implementations should embed UnimplementedRmtaccessmgrServiceServer
// for forward compatibility.
type RmtaccessmgrServiceServer interface {
	GetRemoteAccessConfigByGuid(context.Context, *GetRemoteAccessConfigByGuidRequest) (*GetResourceAccessConfigResponse, error)
}

// UnimplementedRmtaccessmgrServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRmtaccessmgrServiceServer struct{}

func (UnimplementedRmtaccessmgrServiceServer) GetRemoteAccessConfigByGuid(context.Context, *GetRemoteAccessConfigByGuidRequest) (*GetResourceAccessConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRemoteAccessConfigByGuid not implemented")
}
func (UnimplementedRmtaccessmgrServiceServer) testEmbeddedByValue() {}

// UnsafeRmtaccessmgrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RmtaccessmgrServiceServer will
// result in compilation errors.
type UnsafeRmtaccessmgrServiceServer interface {
	mustEmbedUnimplementedRmtaccessmgrServiceServer()
}

func RegisterRmtaccessmgrServiceServer(s grpc.ServiceRegistrar, srv RmtaccessmgrServiceServer) {
	// If the following call pancis, it indicates UnimplementedRmtaccessmgrServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RmtaccessmgrService_ServiceDesc, srv)
}

func _RmtaccessmgrService_GetRemoteAccessConfigByGuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemoteAccessConfigByGuidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RmtaccessmgrServiceServer).GetRemoteAccessConfigByGuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RmtaccessmgrService_GetRemoteAccessConfigByGuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RmtaccessmgrServiceServer).GetRemoteAccessConfigByGuid(ctx, req.(*GetRemoteAccessConfigByGuidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RmtaccessmgrService_ServiceDesc is the grpc.ServiceDesc for RmtaccessmgrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RmtaccessmgrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rmtaccessmgr.v1.RmtaccessmgrService",
	HandlerType: (*RmtaccessmgrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRemoteAccessConfigByGuid",
			Handler:    _RmtaccessmgrService_GetRemoteAccessConfigByGuid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rmtaccessmgr/v1/rmtacessmgr.proto",
}
