// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/open-edge-platform/infra-core/inventory/v2/pkg/api/remoteaccess/v1"
)

// InventoryRACGetter is an autogenerated mock type for the InventoryRACGetter type
type InventoryRACGetter struct {
	mock.Mock
}

type InventoryRACGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryRACGetter) EXPECT() *InventoryRACGetter_Expecter {
	return &InventoryRACGetter_Expecter{mock: &_m.Mock}
}

// GetRemoteAccessConf provides a mock function with given fields: ctx, tenantID, resourceID, timeout
func (_m *InventoryRACGetter) GetRemoteAccessConf(ctx context.Context, tenantID string, resourceID string, timeout time.Duration) (*v1.RemoteAccessConfiguration, error) {
	ret := _m.Called(ctx, tenantID, resourceID, timeout)

	if len(ret) == 0 {
		panic("no return value specified for GetRemoteAccessConf")
	}

	var r0 *v1.RemoteAccessConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (*v1.RemoteAccessConfiguration, error)); ok {
		return rf(ctx, tenantID, resourceID, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) *v1.RemoteAccessConfiguration); ok {
		r0 = rf(ctx, tenantID, resourceID, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RemoteAccessConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, tenantID, resourceID, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRACGetter_GetRemoteAccessConf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemoteAccessConf'
type InventoryRACGetter_GetRemoteAccessConf_Call struct {
	*mock.Call
}

// GetRemoteAccessConf is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - resourceID string
//   - timeout time.Duration
func (_e *InventoryRACGetter_Expecter) GetRemoteAccessConf(ctx interface{}, tenantID interface{}, resourceID interface{}, timeout interface{}) *InventoryRACGetter_GetRemoteAccessConf_Call {
	return &InventoryRACGetter_GetRemoteAccessConf_Call{Call: _e.mock.On("GetRemoteAccessConf", ctx, tenantID, resourceID, timeout)}
}

func (_c *InventoryRACGetter_GetRemoteAccessConf_Call) Run(run func(ctx context.Context, tenantID string, resourceID string, timeout time.Duration)) *InventoryRACGetter_GetRemoteAccessConf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *InventoryRACGetter_GetRemoteAccessConf_Call) Return(_a0 *v1.RemoteAccessConfiguration, _a1 error) *InventoryRACGetter_GetRemoteAccessConf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRACGetter_GetRemoteAccessConf_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) (*v1.RemoteAccessConfiguration, error)) *InventoryRACGetter_GetRemoteAccessConf_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryRACGetter creates a new instance of InventoryRACGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRACGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRACGetter {
	mock := &InventoryRACGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
